### ISSUE TITLE
Plan to release training code and pre-trained model for direction prediction?

### ISSUE THREAD

**Issue by Shanmy** [jinsungit/hiddenfootprints#1]
Hi! 

I'm wondering if you have any plans in the future to release (i) the training code and (ii) the pre-trained model and inference code for walking direction prediction. I only see inference code for walkability, but I'm quite interested in the direction prediction results shown in your paper (Fig. 7).

Thanks for the great work and the released code again. :)

**Comment by jinsungit** [comment]
Hi Shanmy,

Thanks for your interest. Unfortunately, there is currently no plan to further release these parts as the project is no longer active.
